modLoader="javafml"
loaderVersion="[36,)"
logoFile="HellasDeck.png"
license="Restricted"

[[mods]]
modId="hellasdeck"
version="3.0.2"
displayName="HellasDeck"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
'''

[[dependencies.hellasdeck]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellasdeck]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellasdeck]]
modId="pixelmon"
mandatory=true
versionRange="[9.1.12,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hellasdeck]]
modId="hellascontrol"
mandatory=true
versionRange="[2.0.0,)"
ordering="NONE"
side="BOTH"
